# Project-wide Gradle settings.
# org.gradle.jvmargs is defined at the bottom
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete"
kotlin.code.style=official

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and none from the library's dependencies,
# thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true

# Enable Kotlin incremental compilation
kotlin.incremental=true
org.gradle.configuration-cache=true

org.gradle.java.home=C:/Program Files/Java/java-21-openjdk-21.0.4.0.7-1.win.jdk.x86_64

# Gradle'ın arka planda çalışmaya devam etmesini sağlar (Başlatma süresini kısaltır)
org.gradle.daemon=true

# Bağımsız modülleri aynı anda paralel olarak derler
org.gradle.parallel=true

# Derleme önbelleğini açar, değişmeyen kısımları tekrar derlemez
org.gradle.caching=true

# Sadece ilgili modülleri konfigüre eder (Çok modüllü projelerde çok etkilidir)
org.gradle.configureondemand=true

# Gradle'a daha fazla RAM verin (Projenizin büyüklüğüne göre 4g veya 8g yapabilirsiniz)
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US